spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowed-methods: GET,PUT,POST,DELETE
            allowedHeaders: "Authorization,Cache-Control,Content-Type"
            maxAge: 3600
            allowCredentials: true
      routes:
        - id: BOOK-SERVICE
            predicates:
              - Path=/api/categories/**
            uri: http://book-service:8080
        - id: BOOK-SERVICE
            predicates:
              - Path=/api/books/**
            uri: http://book-service:8080
        - id: USER-SERVICE
            predicates:
              - Path=/api/users/**
            uri: http://book-service:8081

server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: debug
